name: "Modpack Utils"
description: "Modpack Utils"
inputs:
  action:
    description: "The action to perform"
    required: true
  api:
    description: "The remote url of the web api"
    required: false
    default: "https://packs.macarena.ceo/api"
  web_token:
    description: "The web api token"
    required: false
  github_token:
    description: "The github tokn"
    required: false
  dropbox_token:
    description: "The dropbox access token"
    required: false
  dropbox_path:
    description: "The dropbox path"
    required: false
    default: ""
runs:
  using: "node12"
  main: dist/index.js
branding:
  color: "purple"
  icon: "arrow-up-circle"
