name: "Modpack Utils"
description: "Modpack Utils"
inputs:
  token:
    description: "The github token"
    required: true
  action:
    description: "The action to perform"
    required: true
  api:
    description: "The remote url of the web api"
    required: false
    default: "https://packs.macarena.ceo/api"
  dropbox_token:
    description: "The dropbox access token"
    required: false
  web_token:
    description: "The web api token"
    required: false
runs:
  using: "node12"
  main: dist/index.js
branding:
  color: "purple"
  icon: "arrow-up-circle"
