name: "Modpack Utils"
description: "Modpack Utils"
inputs:
  token:
    description: "The github token"
    required: true
  action:
    description: "The action to perform"
    required: true
  pack:
    description: "The pack ID"
    required: true
runs:
  using: "node12"
  main: dist/index.js
branding:
  color: "purple"
  icon: "arrow-up-circle"
